### ISSUE TITLE
Adding support for multiple nanoleaf setups

### ISSUE THREAD

**Issue by kartbala** [paulrosania/picoleaf#1]
Huge fan of this package. I'm a *very* novice dev, but a huge nanoleaf fan. Would love  to eventually get this to support multiple setups.

**Comment by tessro** [comment]
Thanks! This is on my radar. The way I would like to implement this is to add a `-f <path>` flag that lets you specify different config files with separate tokens. This would also allow for flexing other configuration on a per device basis in the future. It should be a simple change, I just haven't gotten around to it yet! Thanks for opening an issue.

**Comment by tessro** [comment]
`-f` argument added in [v1.3.0](https://github.com/paulrosania/picoleaf/releases/tag/v1.3.0).
